name: Delete Unused Caches

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      # Do other steps like checkout, install, compile, etc.
      - uses: MyAlbum/purge-cache@master
        with:
          max-age: 1800 # Cache max 7 days since last use (this is the default)
          debug: true # Set to true to output debug info